import './globals.scss'
import type { Metadata } from 'next'
import { Inter, Source_Sans_3 } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const source = Source_Sans_3({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={source.className}>{children}</body>
    </html>
  )
}
